# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               The Hitchhiker's Guide to the Data Galaxy
tagline:             데이터 은하수를 여행하는 히치하이커를 위한 안내서
description:         'This is a blog about data analysis and financial engineering. Made by <a href="https://twitter.com/yui7890" target="_blank">@yui7890</a>.'
url:                 ""
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              HKim
  url:               https://twitter.com/yui7890
  email:

# Custom vars
version:             1.0.0

markdown: kramdown
gems:
  - jekyll-paginate
